name: PyPI Release

on:
  push:
    branches:
      - main
    paths:
      - 'pypi/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment target (testpypi or pypi)'
        required: true
        default: 'testpypi'
        type: choice
        options:
          - testpypi
          - pypi

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          path: pypi/

      - uses: astral-sh/setup-uv@v5
        with:
          version: 'latest'
          pyproject-file: 'pyproject.toml'

      - name: build release distributions
        run: |
          cd pypi
          uv build

      - name: upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: pypi/dist/

  publish-testpypi:
    runs-on: ubuntu-latest
    needs:
      - release-build
    if: github.event.inputs.environment == 'testpypi' || github.event_name == 'push'
    permissions:
      id-token: write

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4
        with:
          repository-url: https://test.pypi.org/legacy/

  publish-pypi:
    runs-on: ubuntu-latest
    needs:
      - release-build
    if: github.event.inputs.environment == 'pypi'
    permissions:
      id-token: write

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4
