name: PyPI

on:
  push:
    branches:
      - main
    paths:
      - 'pypi/**'
  workflow_dispatch:

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          path: pypi/

      - uses: astral-sh/setup-uv@v5
        with:
          version: 'latest'
          pyproject-file: 'pypi/pyproject.toml'

      - name: build release distributions
        run: uv build

      - name: upload windows dists
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      id-token: write

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4
